import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import ClientProviders from "./providers";

const poppins = Poppins({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
  variable: '--font-poppins',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.style} font-poppins antialiased scroll-smooth w-full h-full light bg-background text-foreground`}>
        <ClientProviders>
          {children}
        </ClientProviders>
      </body>
    </html>
  );
}
